version: '3'
services:
  app:
    container_name: app
    image: tequelequeteque/app_full_cycle:latest
    build: .
    working_dir: /app
    env_file: .env
    volumes:
      - .:/app
    ports:
      - ${APP_PORT}:${APP_PORT}